services:
  fluentd:
    container_name: multi-process-ex
    image: psyoblade/data-engineer-fluentd:3.1
    user: root
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ./source:/fluentd/source
      - ./target:/fluentd/target
    ports:
      - 9880:9880
      - 9881:9881
      - 24224:24224
      - 24224:24224/udp
    networks:
      - default
    entrypoint: [ "fluentd" ]

networks:
  default:
    name: day2_ex8_network
