services:
  mysql:
    container_name: mysql
    image: psyoblade/data-engineer-mysql:1.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - '3306:3306'
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 3s
      timeout: 1s
      retries: 3
    volumes:
      - ./mysql/etc:/etc/mysql/conf.d
  mongo:
    image: mongo:6.0.22
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
  notebook:
    container_name: notebook
    user: root
    privileged: true
    image: psyoblade/data-engineer-notebook:1.9.0
    restart: always
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - GRANT_SUDO=yes
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    ports:
      - "4040-4049:4040-4049"
      - "8080:8080"
      - "8888:8888"
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5.9
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: psyoblade/data-engineer-kafka:1.2
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: INTERNAL
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    volumes:
      - ./kafka-data:/tmp/kraft-combined-logs
  cassandra:
    container_name: cassandra
    image: cassandra:4.1.8
    ports:
      - "7001:7000"

networks:
  default:
    name: advanced_day3_network

