services:
  fluentd:
    container_name: fluentd
    image: psyoblade/data-engineer-fluentd:3.1
    user: root
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
    working_dir: /home/root

networks:
  default:
    name: day2_quiz4_network
