services:
  fluentd:
    container_name: multi-process
    image: psyoblade/data-engineer-fluentd:3.1
    stdin_open: true
    tty: true
    user: root
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ./source:/fluentd/source
      - ./target:/fluentd/target
    ports:
      - 9880:9880
      - 24224:24224
      - 24224:24224/udp
    networks:
      - default
    entrypoint: [ "fluentd" ]

networks:
  default:
    name: day2_ex7_network
