version: "3"

services:
  fluentd:
    container_name: fluentd
    image: psyoblade/data-engineer-fluentd:2.2
    user: root
    tty: true
    working_dir: /home/root
    volumes:
      - ./fluentd/config:/fluentd/config
      - ./fluentd/source:/fluentd/source
    environment:
      - TZ=Asia/Seoul
    ports:
      - 9881:9881
  zookeeper:
    container_name: zookeeper
    image: psyoblade/data-engineer-zookeeper:1.0
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: psyoblade/data-engineer-kafka:1.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "movies:1:1"
      KAFKA_HEAP_OPTS: "-Xmx400m -Xms400m"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mysql:
    container_name: mysql
    image: psyoblade/data-engineer-mysql:1.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
      MYSQL_USER: scott
      MYSQL_PASSWORD: tiger
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 3s
      timeout: 1s
      retries: 3
    volumes:
      - ./mysql/etc:/etc/mysql/conf.d
  notebook:
    container_name: notebook
    user: jovyan
    privileged: true
    image: psyoblade/data-engineer-notebook:1.7.5
    restart: always
    volumes:
      - ./notebooks/work:/home/jovyan/work
    environment:
      - GRANT_SUDO=yes
    ports:
      - "4040-4049:4040-4049"
      - "8080:8080"
      - "8888:8888"
  druid:
    container_name: druid
    image: kaplanmaxe/docker-druid-quickstart
    ports:
      - "8088:8888"
    expose:
      - "8082"
    entrypoint: [ "./start-micro-quickstart" ]
    volumes:
      - ./druid/data/wordcount-v1-index.json:/apache-druid-0.16.1-incubating/quickstart/tutorial/wordcount-v1-index.json
      - ./druid/data/wordcount-v1-data.json:/apache-druid-0.16.1-incubating/quickstart/tutorial/wordcount-v1-data.json
  turnilo:
    container_name: turnilo
    image: uchhatre/turnilo
    depends_on:
      - druid
    ports:
      - "9091:9090"
    environment:
      CONFIG_FILE: "/etc/config/turnilo/config.yml"
    volumes:
      - ./turnilo/config/new-config.yml:/etc/config/turnilo/config.yml

networks:
  default:
    name: advanced_day5_network
